# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

TEMPLATE = app
TARGET = console_test
DESTDIR = ../x64/Debug
QT += core gui
CONFIG += debug console
DEFINES += QT_LARGEFILE_SUPPORT QT_DLL
INCLUDEPATH += . \
    ./GeneratedFiles/Debug
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/debug
OBJECTS_DIR += debug
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(console_test.pri)
