import vtk

textMapper = vtk.vtkTextMapper()
tprop = textMapper.GetTextProperty()
tprop.SetFontFamilyToArial()
tprop.SetFontSize(10)
tprop.BoldOn()
tprop.ShadowOn()
tprop.SetColor(1, 0, 0)
textActor = vtk.vtkActor2D()
textActor.VisibilityOff()
textActor.SetMapper(textMapper)
textMapper.SetInput("(%.6f, %.6f, %.6f)"%(1.2, 2.3, 432.0))
textActor.SetPosition(100, 100)
textActor.VisibilityOn()

ren = vtk.vtkRenderer()
renWin = vtk.vtkRenderWindow()
renWin.AddRenderer(ren)
iren = vtk.vtkRenderWindowInteractor()
iren.SetRenderWindow(renWin)
ren.AddActor(textActor)
ren.SetBackground(1, 1, 1)
renWin.SetSize(300, 300)
ren.ResetCamera()
iren.Initialize()
renWin.Render()
iren.Start()